services:
  vllm:
    image: vllm/vllm-openai-xpu:v0.27.1
    container_name: vllm

    # https://recipes.vllm.ai/Qwen/Qwen3.8-27B
    command: >
      cyankiwi/Qwen3.8-27B-AWQ-INT4
      --served-model-name "Qwen3.8-27B-AWQ-INT4"
      --gpu-memory-utilization 0.95
      --download-dir /models
      --host 0.0.0.0
      --port 8000
      --no-enable-prefix-caching
      --max-model-len auto
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --mm-encoder-tp-mode data
      --tensor-parallel-size 1
      --kv-cache-dtype fp8
      --speculative-config '{"method":"mtp","num_speculative_tokens":4}'
    shm_size: "32gb"
    ulimits:
      memlock: -1
      stack: 67108864
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - render
      - video
    volumes:
      - /dev/dri/by-path:/dev/dri/by-path
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./models:/models
      - vllm-cache:/root/.cache/vllm
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 100
      start_period: 300s

volumes:
  vllm-cache: